name = "BarnesDoubleGamma"
uuid = "8c4ec0a7-3a81-41b6-9d5f-01f75984e8d3"
authors = ["Paul-Roux-Phys <paul.roux@phys.ens.fr> and contributors"]
version = "1.2.5"

[deps]
Arblib = "fb37089c-8514-4489-9461-98f9c8763369"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
Arblib = "1"
QuadGK = "2"
SpecialFunctions = "2"
julia = "1.4"
